project_id = "sumdmjypjddcaukudbus"

[functions.get-mapbox-token]
verify_jwt = true

[functions.analyze-company]
verify_jwt = false

[functions.search-places]
verify_jwt = false

[functions.enrich-prospect]
verify_jwt = false

[functions.save-prospect]
verify_jwt = true

[functions.get-favorites]
verify_jwt = true

[functions.update-prospect-notes]
verify_jwt = true
